basic_settings:
  site_title: Josef Behr
  site_tagline: Man muß das Unmögliche versuchen, um das Mögliche zu erreichen. - Hesse
  favicon_image: /images/favicon.png

header_settings:
  logo_image: 
  logo_width: 200
  overlay_opacity: 0.7

menu_settings:
  menu_items:
    - title: 'Blog'
      url: '/'
    - title: 'Was?'
      url: '/was'
    - title: 'Kontakt'
      url: '/kontakt'

grid_settings:
  grid_spacing: 10

contact_settings:
  form_action: 'https://formspree.io/f/mbjpbzdr'
  confirmation_url: '/thanks'
  email_subject: 'Kontaktanfrage Josef Behr'
  send_button_text: 'Absenden'

social_settings:
  facebook_url: 'https://www.facebook.com/sbjdgldsbuvspod/'
  twitter_url: ''
  instagram_url: 'https://instagram.com/ecstaticjosef'
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: 'https://github.com/josefbehr'
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: 'https://bandcamp.com/josef'
  linkedin_url: 'https://linkedin.com/in/josefbehr'

color_settings:
  background_color: '#222222'
  background_alt_color: '#444444'
  text_dark_color: '#4f708d'
  text_medium_color: '#8C9Aa9'
  text_light_color: '#cccccc'
  accent_color: '#9a6673'
  border_color: '#2e506a'
  overlay_background_color: '#161B21'
  overlay_text_color: '#ffffff'
  error_color: '#3f2629'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Kanit:300,400|Rubik:400,400i,600" rel="stylesheet">'
  title_font: '"Kanit", sans-serif'
  body_font: '"Rubik", sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 400
    letter_spacing: 0
  site_tagline:
    small_size: 16
    medium_size: 17
    large_size: 18
    weight: 400
    letter_spacing: 0
    line_height: 1.5
  menu:
    small_size: 30
    medium_size: 17
    large_size: 18
    weight: 400
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 400
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 400
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 400
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 400
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""
